#!/bin/sh -e

# Source debconf library
. /usr/share/debconf/confmodule

#Récupération de la variable version depuis la configuration debian
db_get chalets/version
version=$RET

#Récupération de la variable environment depuis la configuration debian
db_get chalets/env
env=$RET

#Lancement du chalets.jar (serveur services REST)
java -jar /srv/chalets/chalets-$version.jar server > /dev/null &

# Lancement de liquibase
cd /tmp/chalets
chmod +x ./liquibase
./liquibase migrate

# Téléchargement de la configuration
curl "http://www.ludine.ch/cd/config/$env.jpg" --create-dirs -o /etc/chalets/logo.jpg

#Création d'un lien symbolique sur la configuration
ln -s /etc/chalets/ /var/www/html/config
chmod -R 777 /etc/chalets

#Arret de la configuration DEBIAN (IMPORTANT !)
db_stop
